id: IB32F1FDA
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T23:51:10.620991'
last_modified: '2022-06-18T23:51:10.621004'
parser: null
source_metadata:
  title: Vinayasūtra of Guṇaprabha (Gong dkar block print), colophon excerpt
  author: ཡོན་ཏན་འོད།
  description: 'Digital version 1.0 {Tibetan}; master xml (completed: 2016-02-07);
    revised, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:ཚེ་རིང་གྲོང་ཤར། (ut)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:Mathias Fermer (mf)
  text_witnesses: https://sakyaresearch.org/sources/739
  bases:
    1e20:
      title: Vinayasūtra of Guṇaprabha (Gong dkar block print), colophon excerpt
      order: 1
      base_file: 1e20.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
